name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set pip install version
      run: |
        python -m pip install pip==23.1
    - name: Install dependencies
      run: |
        pip install --use-pep517 -r requirements.txt
    - name: Check formatting
      run: |
        black --check bugan
    - name: Test with pytest
      run: |
        pytest

    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
